const ataTemplate = '<p align="center"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>ATA DE AUDIÊNCIA PÚBLICA Nº [</strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>inserir nº da audiência pública</strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>]</strong></span></span></p>'+
'<p align="center"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">Categoria: [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir categoria</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">]</span></span></p>'+
'<p align="justify"> </p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>1. </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><u><strong>Data, Horário e Local</strong></u></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>: </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">A audiência pública foi realizada na data de [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">data de realização</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], às </span></span>[<span style="font-family: Tahoma, serif;"><span style="font-size: small;">horário da reunião</span></span>], <span style="font-family: Tahoma, serif;"><span style="font-size: small;">no endereço localizado à [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">endereço completo do local da reunião</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">]. </span></span></p>'+
'<p align="justify"> </p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>2. </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><u><strong>Convocação</strong></u></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>:</strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"> Cumpridas todas as formalidades, nas formas da legislação [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">informar legislação</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], foi instalada a audiência pública.</span></span></p>'+
'<p align="justify"> </p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>3. </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><u><strong>Participantes</strong></u></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>:</strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"> Estiveram presentes a esta Audiência Pública os seguintes participantes:</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>3.1. Convocados:</strong></span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">Inserir nome completo</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], representando [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir órgão/entidade/empresa</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">];</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">Inserir nome completo</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], representando [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir órgão/entidade/empresa</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">];</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">Inserir nome completo</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], representando [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir órgão/entidade/empresa</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">];</span></span></p>'+
'<p align="justify"> </p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>3.2. Interessados:</strong></span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">Inserir nome completo</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">];</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">Inserir nome completo</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">];</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">Inserir nome completo</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">].</span></span></p>'+
'<p align="justify"> </p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>4. </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><u><strong>Mesa</strong></u></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>:</strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"> Os presentes a esta Audiência escolheram para figurar como Presidente desta Audiência, o(a) Sr(a). [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir nome</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir nacionalidade</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir estado civil</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir profissão</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir endereço completo</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], assim como também escolheram, para figurar como Secretário, o(a) Sr(a). [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir nome</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir nacionalidade</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir estado civil</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir profissão</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir endereço completo</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">].</span></span></p>'+
'<p align="justify"> </p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>5. </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><u><strong>Objetivo(s)</strong></u></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>:</strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"> [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir objetivo(s)</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">].</span></span></p>'+
'<p align="justify"> </p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>6. </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><u><strong>Pauta</strong></u></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">:</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">1ª assunto da pauta</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">];</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">2ª assunto da pauta</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">];</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">3ª assunto da pauta</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">];</span></span></p>'+
'<p align="justify"> </p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>7. </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><u><strong>Decisões</strong></u></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>:</strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"> Após exame e discussão dos itens constantes da Pauta, os participantes decidiram:</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir primeira decisão</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">];</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir segunda decisão</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">];</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir terceira decisão</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">].</span></span></p>'+
'<p align="justify"> </p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>8. </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><u><strong>Prazos e Responsáveis pelo Cumprimento das Decisões</strong></u></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>: </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">Ficou acertado entre os participantes que serão definidos prazos e responsáveis pelo cumprimento das decisões tomadas, da seguinte maneira:</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">A decisão 1 será executada por [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir nome do responsável</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], que deverá apresentar o cumprimento da meta, ou a devida justificativa, no prazo de até [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">] dias contados da realização desta audiência pública;</span></span></p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">A decisão 2 será executada por [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir nome do responsável</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], que deverá apresentar o cumprimento da meta, ou a devida justificativa, no prazo de até [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">] dias contados da realização desta audiência pública.</span></span></p>'+
'<p align="justify"> </p>'+
'<p align="justify"><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><strong>9. </strong></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"><u><strong>Encerramento:</strong></u></span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;"> Nada mais havendo a tratar, foram encerrados os trabalhos e lavrada esta ata que, após lida e aprovada pelos presentes, foi assinada pelo(a) Presidente da Mesa, o(a) Sr(a). [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir nome do presidente da mesa</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], por mim, [</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir nome do secretário da mesa</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">], secretário dos trabalhos, e, abaixo, por todos os participantes convidados que estiveram presentes à audiência.</span></span></p>'+
'<p align="justify"><a name="_GoBack"></a> </p>'+
'<p align="center"><span style="font-family: Tahoma, serif;"><span style="font-size: small;">[</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">inserir assinaturas dos convidados presentes</span></span><span style="font-family: Tahoma, serif;"><span style="font-size: small;">]</span></span></p>';
	
module.exports = ataTemplate